// TypeScript declarations for external modules without types
declare module 'lucide-react' {
  import * as React from 'react'

  export interface LucideIconProps extends React.SVGProps<SVGSVGElement> {
    size?: number
    color?: string
    strokeWidth?: number
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = React.ForwardRefExoticComponent<LucideIconProps & React.RefAttributes<SVGSVGElement>>

  // Common icons used in this project
  export const Activity: LucideIcon
  export const AlertCircle: LucideIcon
  export const AlertOctagon: LucideIcon
  export const AlertTriangle: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignJustify: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignRight: LucideIcon
  export const Anchor: LucideIcon
  export const Aperture: LucideIcon
  export const Archive: LucideIcon
  export const ArchiveRestore: LucideIcon
  export const ArrowBigDown: LucideIcon
  export const ArrowBigLeft: LucideIcon
  export const ArrowBigRight: LucideIcon
  export const ArrowBigUp: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowDownCircle: LucideIcon
  export const ArrowDownLeft: LucideIcon
  export const ArrowDownRight: LucideIcon
  export const ArrowDownFromLine: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowLeftCircle: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowRightCircle: LucideIcon
  export const ArrowUp: LucideIcon
  export const ArrowUpCircle: LucideIcon
  export const ArrowUpDown: LucideIcon
  export const ArrowLeftRight: LucideIcon
  export const ArrowDownUp: LucideIcon
  export const ArrowUpFromLine: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const ArrowDownToLine: LucideIcon
  export const ArrowUpLeft: LucideIcon
  export const ArrowDownToDot: LucideIcon
  export const ArrowUpToDot: LucideIcon
  export const AtSign: LucideIcon
  export const Award: LucideIcon
  export const Baby: LucideIcon
  export const Backpack: LucideIcon
  export const Badge: LucideIcon
  export const BadgeCheck: LucideIcon
  export const BadgePercent: LucideIcon
  export const BadgePlus: LucideIcon
  export const BadgeMinus: LucideIcon
  export const BadgeX: LucideIcon
  export const Ban: LucideIcon
  export const Bandage: LucideIcon
  export const Banknote: LucideIcon
  export const BarChart: LucideIcon
  export const BarChart2: LucideIcon
  export const BarChart3: LucideIcon
  export const BarChart4: LucideIcon
  export const BarChartHorizontal: LucideIcon
  export const Baseline: LucideIcon
  export const Bath: LucideIcon
  export const Battery: LucideIcon
  export const BatteryCharging: LucideIcon
  export const BatteryLow: LucideIcon
  export const BatteryMedium: LucideIcon
  export const Beaker: LucideIcon
  export const Bean: LucideIcon
  export const BeanOff: LucideIcon
  export const Bed: LucideIcon
  export const BedDouble: LucideIcon
  export const BedSingle: LucideIcon
  export const Beef: LucideIcon
  export const Beer: LucideIcon
  export const Bell: LucideIcon
  export const BellDot: LucideIcon
  export const BellMinus: LucideIcon
  export const BellOff: LucideIcon
  export const BellPlus: LucideIcon
  export const BellRing: LucideIcon
  export const Bike: LucideIcon
  export const Binary: LucideIcon
  export const Biohazard: LucideIcon
  export const Bird: LucideIcon
  export const Bitcoin: LucideIcon
  export const Bluetooth: LucideIcon
  export const BluetoothConnected: LucideIcon
  export const BluetoothOff: LucideIcon
  export const BluetoothSearching: LucideIcon
  export const Bold: LucideIcon
  export const Bolt: LucideIcon
  export const Bomb: LucideIcon
  export const Bone: LucideIcon
  export const Book: LucideIcon
  export const BookOpen: LucideIcon
  export const BookMarked: LucideIcon
  export const BookText: LucideIcon
  export const BookUp: LucideIcon
  export const BookUser: LucideIcon
  export const Bookmark: LucideIcon
  export const BookmarkMinus: LucideIcon
  export const BookmarkPlus: LucideIcon
  export const BookmarkX: LucideIcon
  export const Bot: LucideIcon
  export const Box: LucideIcon
  export const BoxSelect: LucideIcon
  export const Boxes: LucideIcon
  export const Braces: LucideIcon
  export const Brackets: LucideIcon
  export const Brain: LucideIcon
  export const BrainCircuit: LucideIcon
  export const BrickWall: LucideIcon
  export const Briefcase: LucideIcon
  export const BriefcaseBusiness: LucideIcon
  export const BriefcaseConveyorBelt: LucideIcon
  export const BriefcaseMedical: LucideIcon
  export const BringToFront: LucideIcon
  export const Brush: LucideIcon
  export const Bug: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Bus: LucideIcon
  export const BusFront: LucideIcon
  export const CableCar: LucideIcon
  export const Cake: LucideIcon
  export const Calculator: LucideIcon
  export const Calendar: LucideIcon
  export const CalendarCheck: LucideIcon
  export const CalendarClock: LucideIcon
  export const CalendarDays: LucideIcon
  export const CalendarHeart: LucideIcon
  export const CalendarMinus: LucideIcon
  export const CalendarOff: LucideIcon
  export const CalendarPlus: LucideIcon
  export const CalendarRange: LucideIcon
  export const CalendarX: LucideIcon
  export const Camera: LucideIcon
  export const CameraOff: LucideIcon
  export const Car: LucideIcon
  export const CarFront: LucideIcon
  export const CarTaxiFront: LucideIcon
  export const Carrot: LucideIcon
  export const CaseSensitive: LucideIcon
  export const CassetteTape: LucideIcon
  export const Cast: LucideIcon
  export const Castle: LucideIcon
  export const Cat: LucideIcon
  export const Check: LucideIcon
  export const CheckCheck: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const CheckSquare: LucideIcon
  export const ChefHat: LucideIcon
  export const Cherry: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronFirst: LucideIcon
  export const ChevronLast: LucideIcon
  export const ChevronsDown: LucideIcon
  export const ChevronsUp: LucideIcon
  export const ChevronsLeft: LucideIcon
  export const ChevronsRight: LucideIcon
  export const Chrome: LucideIcon
  export const Church: LucideIcon
  export const Cigarette: LucideIcon
  export const Circle: LucideIcon
  export const CircleAlert: LucideIcon
  export const CircleArrowDown: LucideIcon
  export const CircleArrowLeft: LucideIcon
  export const CircleArrowRight: LucideIcon
  export const CircleArrowUp: LucideIcon
  export const CircleCheck: LucideIcon
  export const CircleCheckBig: LucideIcon
  export const CircleDash: LucideIcon
  export const CircleDot: LucideIcon
  export const CircleEllipsis: LucideIcon
  export const CircleEqual: LucideIcon
  export const CircleFadingPlus: LucideIcon
  export const CircleGauge: LucideIcon
  export const CircleHelp: LucideIcon
  export const CircleMinus: LucideIcon
  export const CirclePause: LucideIcon
  export const CirclePlay: LucideIcon
  export const CirclePlus: LucideIcon
  export const CircleSlash: LucideIcon
  export const CircleStop: LucideIcon
  export const CircleX: LucideIcon
  export const CircuitBoard: LucideIcon
  export const Citrus: LucideIcon
  export const Clapperboard: LucideIcon
  export const Clipboard: LucideIcon
  export const ClipboardCheck: LucideIcon
  export const ClipboardCopy: LucideIcon
  export const ClipboardEdit: LucideIcon
  export const ClipboardList: LucideIcon
  export const ClipboardMinus: LucideIcon
  export const ClipboardPlus: LucideIcon
  export const ClipboardType: LucideIcon
  export const ClipboardX: LucideIcon
  export const Clock: LucideIcon
  export const Clock1: LucideIcon
  export const Clock2: LucideIcon
  export const Clock3: LucideIcon
  export const Clock4: LucideIcon
  export const Clock5: LucideIcon
  export const Clock6: LucideIcon
  export const Clock7: LucideIcon
  export const Clock8: LucideIcon
  export const Clock9: LucideIcon
  export const Clock10: LucideIcon
  export const Clock11: LucideIcon
  export const Clock12: LucideIcon
  export const Cloud: LucideIcon
  export const CloudCog: LucideIcon
  export const CloudDrizzle: LucideIcon
  export const CloudFog: LucideIcon
  export const CloudHail: LucideIcon
  export const CloudLightning: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudMoonRain: LucideIcon
  export const CloudOff: LucideIcon
  export const CloudRain: LucideIcon
  export const CloudRainWind: LucideIcon
  export const CloudSnow: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudSunRain: LucideIcon
  export const Cloudy: LucideIcon
  export const Clover: LucideIcon
  export const Club: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const CodeXml: LucideIcon
  export const Codepen: LucideIcon
  export const Codesandbox: LucideIcon
  export const Coffee: LucideIcon
  export const Cog: LucideIcon
  export const Coins: LucideIcon
  export const Columns: LucideIcon
  export const Columns2: LucideIcon
  export const Columns3: LucideIcon
  export const Columns4: LucideIcon
  export const Combine: LucideIcon
  export const Command: LucideIcon
  export const Compass: LucideIcon
  export const Component: LucideIcon
  export const Computer: LucideIcon
  export const ConciergeBell: LucideIcon
  export const Cone: LucideIcon
  export const Construction: LucideIcon
  export const Contact: LucideIcon
  export const Contact2: LucideIcon
  export const Container: LucideIcon
  export const Contrast: LucideIcon
  export const Cookie: LucideIcon
  export const CookingPot: LucideIcon
  export const Copy: LucideIcon
  export const CopyCheck: LucideIcon
  export const CopyMinus: LucideIcon
  export const CopyPlus: LucideIcon
  export const CopySlash: LucideIcon
  export const CopyX: LucideIcon
  export const Copyleft: LucideIcon
  export const Copyright: LucideIcon
  export const CornerDownLeft: LucideIcon
  export const CornerDownRight: LucideIcon
  export const CornerLeftDown: LucideIcon
  export const CornerLeftUp: LucideIcon
  export const CornerRightDown: LucideIcon
  export const CornerRightUp: LucideIcon
  export const CornerUpLeft: LucideIcon
  export const CornerUpRight: LucideIcon
  export const Cpu: LucideIcon
  export const CreativeCommons: LucideIcon
  export const CreditCard: LucideIcon
  export const Croissant: LucideIcon
  export const Crop: LucideIcon
  export const Cross: LucideIcon
  export const Crosshair: LucideIcon
  export const Crown: LucideIcon
  export const Cuboid: LucideIcon
  export const CupSoda: LucideIcon
  export const Currency: LucideIcon
  export const Cylinder: LucideIcon
  export const Database: LucideIcon
  export const DatabaseBackup: LucideIcon
  export const DatabaseZap: LucideIcon
  export const Delete: LucideIcon
  export const Dessert: LucideIcon
  export const Diameter: LucideIcon
  export const Diamond: LucideIcon
  export const DiamondMinus: LucideIcon
  export const DiamondPlus: LucideIcon
  export const Dice1: LucideIcon
  export const Dice2: LucideIcon
  export const Dice3: LucideIcon
  export const Dice4: LucideIcon
  export const Dice5: LucideIcon
  export const Dice6: LucideIcon
  export const Dices: LucideIcon
  export const Diff: LucideIcon
  export const Disc: LucideIcon
  export const Disc2: LucideIcon
  export const Disc3: LucideIcon
  export const Divide: LucideIcon
  export const Dna: LucideIcon
  export const Dock: LucideIcon
  export const Dog: LucideIcon
  export const DollarSign: LucideIcon
  export const Donut: LucideIcon
  export const DoorClosed: LucideIcon
  export const DoorOpen: LucideIcon
  export const Dot: LucideIcon
  export const Download: LucideIcon
  export const DownloadCloud: LucideIcon
  export const Droplet: LucideIcon
  export const Droplets: LucideIcon
  export const Drum: LucideIcon
  export const Drumstick: LucideIcon
  export const Dvd: LucideIcon
  export const Ear: LucideIcon
  export const EarOff: LucideIcon
  export const Earth: LucideIcon
  export const EarthLock: LucideIcon
  export const Eclipse: LucideIcon
  export const Edit: LucideIcon
  export const Edit2: LucideIcon
  export const Edit3: LucideIcon
  export const Egg: LucideIcon
  export const EggFried: LucideIcon
  export const EggOff: LucideIcon
  export const Ellipsis: LucideIcon
  export const EllipsisVertical: LucideIcon
  export const Equal: LucideIcon
  export const EqualNot: LucideIcon
  export const EqualApproximately: LucideIcon
  export const Eraser: LucideIcon
  export const EthernetPort: LucideIcon
  export const Euro: LucideIcon
  export const Expand: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const EyeClosed: LucideIcon
  export const EyeOff: LucideIcon
  export const Facebook: LucideIcon
  export const Factory: LucideIcon
  export const Fan: LucideIcon
  export const FastForward: LucideIcon
  export const Feather: LucideIcon
  export const Fence: LucideIcon
  export const FerrisWheel: LucideIcon
  export const Figma: LucideIcon
  export const File: LucideIcon
  export const FileArchive: LucideIcon
  export const FileAudio: LucideIcon
  export const FileAudio2: LucideIcon
  export const FileAxis3D: LucideIcon
  export const FileBadge: LucideIcon
  export const FileBarChart: LucideIcon
  export const FileBarChart2: LucideIcon
  export const FileBox: LucideIcon
  export const FileCheck: LucideIcon
  export const FileCheck2: LucideIcon
  export const FileClock: LucideIcon
  export const FileCode: LucideIcon
  export const FileCode2: LucideIcon
  export const FileCog: LucideIcon
  export const FileDiff: LucideIcon
  export const FileDigit: LucideIcon
  export const FileDown: LucideIcon
  export const FileHeart: LucideIcon
  export const FileImage: LucideIcon
  export const FileInput: LucideIcon
  export const FileJson: LucideIcon
  export const FileKey: LucideIcon
  export const FileLineChart: LucideIcon
  export const FileLock: LucideIcon
  export const FileLock2: LucideIcon
  export const FileMinus: LucideIcon
  export const FileMinus2: LucideIcon
  export const FileMusic: LucideIcon
  export const FileOutput: LucideIcon
  export const FilePen: LucideIcon
  export const FilePenLine: LucideIcon
  export const FilePlus: LucideIcon
  export const FilePlus2: LucideIcon
  export const FileQuestion: LucideIcon
  export const FileSearch: LucideIcon
  export const FileSearch2: LucideIcon
  export const FileSignature: LucideIcon
  export const FileSliders: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileStack: LucideIcon
  export const FileSymlink: LucideIcon
  export const FileTerminal: LucideIcon
  export const FileText: LucideIcon
  export const FileType: LucideIcon
  export const FileUp: LucideIcon
  export const FileVideo: LucideIcon
  export const FileVideo2: LucideIcon
  export const FileWarning: LucideIcon
  export const FileX: LucideIcon
  export const FileX2: LucideIcon
  export const Files: LucideIcon
  export const Film: LucideIcon
  export const Filter: LucideIcon
  export const FilterX: LucideIcon
  export const Fingerprint: LucideIcon
  export const Flag: LucideIcon
  export const FlagOff: LucideIcon
  export const FlagTriangleLeft: LucideIcon
  export const FlagTriangleRight: LucideIcon
  export const Flame: LucideIcon
  export const FlameKindling: LucideIcon
  export const Flashlight: LucideIcon
  export const FlashlightOff: LucideIcon
  export const FlaskConical: LucideIcon
  export const FlaskConicalOff: LucideIcon
  export const FlaskRound: LucideIcon
  export const FlipHorizontal: LucideIcon
  export const FlipHorizontal2: LucideIcon
  export const FlipVertical: LucideIcon
  export const FlipVertical2: LucideIcon
  export const Flower: LucideIcon
  export const Flower2: LucideIcon
  export const Focus: LucideIcon
  export const Folder: LucideIcon
  export const FolderArchive: LucideIcon
  export const FolderCheck: LucideIcon
  export const FolderClock: LucideIcon
  export const FolderClosed: LucideIcon
  export const FolderCog: LucideIcon
  export const FolderDot: LucideIcon
  export const FolderDown: LucideIcon
  export const FolderGit: LucideIcon
  export const FolderGit2: LucideIcon
  export const FolderHeart: LucideIcon
  export const FolderInput: LucideIcon
  export const FolderKanban: LucideIcon
  export const FolderKey: LucideIcon
  export const FolderLock: LucideIcon
  export const FolderMinus: LucideIcon
  export const FolderOpen: LucideIcon
  export const FolderOpenDot: LucideIcon
  export const FolderOutput: LucideIcon
  export const FolderPen: LucideIcon
  export const FolderPlus: LucideIcon
  export const FolderRoot: LucideIcon
  export const FolderSearch: LucideIcon
  export const FolderSearch2: LucideIcon
  export const FolderSymlink: LucideIcon
  export const FolderTree: LucideIcon
  export const FolderUp: LucideIcon
  export const FolderX: LucideIcon
  export const Folders: LucideIcon
  export const Footprints: LucideIcon
  export const Forklift: LucideIcon
  export const Forward: LucideIcon
  export const Frame: LucideIcon
  export const Framer: LucideIcon
  export const Frown: LucideIcon
  export const Fuel: LucideIcon
  export const FunctionSquare: LucideIcon
  export const GalleryHorizontal: LucideIcon
  export const GalleryHorizontalEnd: LucideIcon
  export const GalleryVertical: LucideIcon
  export const GalleryVerticalEnd: LucideIcon
  export const Gamepad: LucideIcon
  export const Gamepad2: LucideIcon
  export const GanttChart: LucideIcon
  export const Gauge: LucideIcon
  export const GaugeCircle: LucideIcon
  export const Ghost: LucideIcon
  export const Gift: LucideIcon
  export const GitBranch: LucideIcon
  export const GitBranchPlus: LucideIcon
  export const GitCommit: LucideIcon
  export const GitCommitHorizontal: LucideIcon
  export const GitCommitVertical: LucideIcon
  export const GitCompare: LucideIcon
  export const GitCompareArrows: LucideIcon
  export const GitFork: LucideIcon
  export const GitGraph: LucideIcon
  export const GitMerge: LucideIcon
  export const GitPullRequest: LucideIcon
  export const GitPullRequestArrow: LucideIcon
  export const GitPullRequestClosed: LucideIcon
  export const GitPullRequestDraft: LucideIcon
  export const GitPullRequestCreate: LucideIcon
  export const Github: LucideIcon
  export const Gitlab: LucideIcon
  export const GitCommitHorizontal: LucideIcon
  export const GlassWater: LucideIcon
  export const Glasses: LucideIcon
  export const Globe: LucideIcon
  export const GlobeLock: LucideIcon
  export const Goal: LucideIcon
  export const Gpu: LucideIcon
  export const Grab: LucideIcon
  export const GraduationCap: LucideIcon
  export const Grape: LucideIcon
  export const Grid: LucideIcon
  export const Grid2x2: LucideIcon
  export const Grid3x3: LucideIcon
  export const Grip: LucideIcon
  export const GripHorizontal: LucideIcon
  export const GripVertical: LucideIcon
  export const Group: LucideIcon
  export const Guitar: LucideIcon
  export const Ham: LucideIcon
  export const Hammer: LucideIcon
  export const Hand: LucideIcon
  export const HandCoins: LucideIcon
  export const HandHeart: LucideIcon
  export const HandMetal: LucideIcon
  export const HandPlatter: LucideIcon
  export const HardDrive: LucideIcon
  export const HardDriveDownload: LucideIcon
  export const HardDriveUpload: LucideIcon
  export const HardHat: LucideIcon
  export const Hash: LucideIcon
  export const Haze: LucideIcon
  export const HdmiPort: LucideIcon
  export const Heading: LucideIcon
  export const Heading1: LucideIcon
  export const Heading2: LucideIcon
  export const Heading3: LucideIcon
  export const Heading4: LucideIcon
  export const Headphones: LucideIcon
  export const Headset: LucideIcon
  export const Heart: LucideIcon
  export const HeartCrack: LucideIcon
  export const HeartHandshake: LucideIcon
  export const HeartOff: LucideIcon
  export const HeartPulse: LucideIcon
  export const HelpCircle: LucideIcon
  export const Hexagon: LucideIcon
  export const Highlighter: LucideIcon
  export const History: LucideIcon
  export const Home: LucideIcon
  export const Hop: LucideIcon
  export const HopOff: LucideIcon
  export const Hospital: LucideIcon
  export const Hotel: LucideIcon
  export const Hourglass: LucideIcon
  export const IceCream: LucideIcon
  export const Image: LucideIcon
  export const ImageDown: LucideIcon
  export const ImageMinus: LucideIcon
  export const ImageOff: LucideIcon
  export const ImagePlus: LucideIcon
  export const ImagePlay: LucideIcon
  export const ImageUp: LucideIcon
  export const Images: LucideIcon
  export const Import: LucideIcon
  export const Inbox: LucideIcon
  export const Indent: LucideIcon
  export const IndianRupee: LucideIcon
  export const Infinity: LucideIcon
  export const Info: LucideIcon
  export const Inspect: LucideIcon
  export const Instance: LucideIcon
  export const Italic: LucideIcon
  export const IterationCcw: LucideIcon
  export const IterationCw: LucideIcon
  export const JapaneseYen: LucideIcon
  export const Joystick: LucideIcon
  export const Kanban: LucideIcon
  export const Key: LucideIcon
  export const KeyRound: LucideIcon
  export const Keyboard: LucideIcon
  export const KeyboardMusic: LucideIcon
  export const KeyboardOff: LucideIcon
  export const Lamp: LucideIcon
  export const LampCeiling: LucideIcon
  export const LampDesk: LucideIcon
  export const LampFloor: LucideIcon
  export const LampWallDown: LucideIcon
  export const LampWallUp: LucideIcon
  export const LandPlot: LucideIcon
  export const Landmark: LucideIcon
  export const Languages: LucideIcon
  export const Laptop: LucideIcon
  export const Laptop2: LucideIcon
  export const Lasso: LucideIcon
  export const LassoSelect: LucideIcon
  export const Laugh: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const LayoutGrid: LucideIcon
  export const LayoutList: LucideIcon
  export const LayoutPanelLeft: LucideIcon
  export const LayoutPanelTop: LucideIcon
  export const LayoutTemplate: LucideIcon
  export const Leaf: LucideIcon
  export const LeafyGreen: LucideIcon
  export const Library: LucideIcon
  export const LibraryBig: LucideIcon
  export const LibraryPanel: LucideIcon
  export const LifeBuoy: LucideIcon
  export const Lightbulb: LucideIcon
  export const LightbulbOff: LucideIcon
  export const LineChart: LucideIcon
  export const Link: LucideIcon
  export const Link2: LucideIcon
  export const Link2Off: LucideIcon
  export const Linkedin: LucideIcon
  export const List: LucideIcon
  export const ListChecks: LucideIcon
  export const ListEnd: LucideIcon
  export const ListFilter: LucideIcon
  export const ListFilterPlus: LucideIcon
  export const ListMinus: LucideIcon
  export const ListMusic: LucideIcon
  export const ListOrdered: LucideIcon
  export const ListPlus: LucideIcon
  export const ListRestart: LucideIcon
  export const ListStart: LucideIcon
  export const ListTodo: LucideIcon
  export const ListTree: LucideIcon
  export const ListVideo: LucideIcon
  export const ListX: LucideIcon
  export const Loader: LucideIcon
  export const Loader2: LucideIcon
  export const LoaderPinwheel: LucideIcon
  export const Locate: LucideIcon
  export const Lock: LucideIcon
  export const LockKeyhole: LucideIcon
  export const LockOpen: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const Luggage: LucideIcon
  export const Magnet: LucideIcon
  export const Mail: LucideIcon
  export const MailCheck: LucideIcon
  export const MailMinus: LucideIcon
  export const MailOpen: LucideIcon
  export const MailPlus: LucideIcon
  export const MailQuestion: LucideIcon
  export const MailSearch: LucideIcon
  export const MailWarning: LucideIcon
  export const MailX: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const MapPinOff: LucideIcon
  export const Maximize: LucideIcon
  export const Maximize2: LucideIcon
  export const Medal: LucideIcon
  export const Megaphone: LucideIcon
  export const Meh: LucideIcon
  export const MemoryStick: LucideIcon
  export const Menu: LucideIcon
  export const MessageCircle: LucideIcon
  export const MessageSquare: LucideIcon
  export const MessageCircleCode: LucideIcon
  export const MessageCircleDashed: LucideIcon
  export const MessageCircleHeart: LucideIcon
  export const MessageCircleMore: LucideIcon
  export const MessageCircleOff: LucideIcon
  export const MessageCirclePlus: LucideIcon
  export const MessageCircleQuestion: LucideIcon
  export const MessageCircleReply: LucideIcon
  export const MessageCircleWarning: LucideIcon
  export const MessageCircleX: LucideIcon
  export const MessageSquareCode: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const MessageSquareDiff: LucideIcon
  export const MessageSquareDot: LucideIcon
  export const MessageSquareHeart: LucideIcon
  export const MessageSquareMore: LucideIcon
  export const MessageSquareOff: LucideIcon
  export const MessageSquarePlus: LucideIcon
  export const MessageSquareQuote: LucideIcon
  export const MessageSquareReply: LucideIcon
  export const MessageSquareShare: LucideIcon
  export const MessageSquareText: LucideIcon
  export const MessageSquareWarning: LucideIcon
  export const MessageSquareX: LucideIcon
  export const MessagesSquare: LucideIcon
  export const Mic: LucideIcon
  export const Mic2: LucideIcon
  export const MicOff: LucideIcon
  export const Microphone: LucideIcon
  export const Microscope: LucideIcon
  export const Microwave: LucideIcon
  export const Milestone: LucideIcon
  export const Minimize: LucideIcon
  export const Minimize2: LucideIcon
  export const Minus: LucideIcon
  export const Monitor: LucideIcon
  export const MonitorCheck: LucideIcon
  export const MonitorDot: LucideIcon
  export const MonitorDown: LucideIcon
  export const MonitorOff: LucideIcon
  export const MonitorPause: LucideIcon
  export const MonitorPlay: LucideIcon
  export const MonitorSmartphone: LucideIcon
  export const MonitorSpeaker: LucideIcon
  export const MonitorStop: LucideIcon
  export const MonitorUp: LucideIcon
  export const MonitorX: LucideIcon
  export const Moon: LucideIcon
  export const MoonStar: LucideIcon
  export const MousePointer: LucideIcon
  export const MousePointer2: LucideIcon
  export const MousePointerClick: LucideIcon
  export const Move: LucideIcon
  export const Move3D: LucideIcon
  export const MoveDown: LucideIcon
  export const MoveDownLeft: LucideIcon
  export const MoveDownRight: LucideIcon
  export const MoveHorizontal: LucideIcon
  export const MoveLeft: LucideIcon
  export const MoveRight: LucideIcon
  export const MoveUp: LucideIcon
  export const MoveUpLeft: LucideIcon
  export const MoveUpRight: LucideIcon
  export const MoveVertical: LucideIcon
  export const Music: LucideIcon
  export const Music2: LucideIcon
  export const Music3: LucideIcon
  export const Music4: LucideIcon
  export const Navigation: LucideIcon
  export const Navigation2: LucideIcon
  export const Navigation2Off: LucideIcon
  export const NavigationOff: LucideIcon
  export const Network: LucideIcon
  export const Newspaper: LucideIcon
  export const Nfc: LucideIcon
  export const Notebook: LucideIcon
  export const NotebookPen: LucideIcon
  export const NotebookTabs: LucideIcon
  export const NotebookText: LucideIcon
  export const Nut: LucideIcon
  export const NutOff: LucideIcon
  export const Octagon: LucideIcon
  export const OctagonAlert: LucideIcon
  export const OctagonMinus: LucideIcon
  export const OctagonPause: LucideIcon
  export const OctagonX: LucideIcon
  export const Option: LucideIcon
  export const Outdent: LucideIcon
  export const Package: LucideIcon
  export const Package2: LucideIcon
  export const PackageCheck: LucideIcon
  export const PackageMinus: LucideIcon
  export const PackageOpen: LucideIcon
  export const PackagePlus: LucideIcon
  export const PackageSearch: LucideIcon
  export const PackageX: LucideIcon
  export const PaintBucket: LucideIcon
  export const PaintRoller: LucideIcon
  export const Palette: LucideIcon
  export const Paperclip: LucideIcon
  export const Paragraph: LucideIcon
  export const Parentheses: LucideIcon
  export const ParkingCircle: LucideIcon
  export const ParkingCircleOff: LucideIcon
  export const ParkingMeter: LucideIcon
  export const ParkingSquare: LucideIcon
  export const ParkingSquareOff: LucideIcon
  export const PartyPopper: LucideIcon
  export const Pause: LucideIcon
  export const PauseCircle: LucideIcon
  export const Pen: LucideIcon
  export const PenLine: LucideIcon
  export const PenOff: LucideIcon
  export const PenTool: LucideIcon
  export const Pencil: LucideIcon
  export const PencilLine: LucideIcon
  export const PencilRuler: LucideIcon
  export const Pentagon: LucideIcon
  export const Percent: LucideIcon
  export const PersonStanding: LucideIcon
  export const Phone: LucideIcon
  export const PhoneCall: LucideIcon
  export const PhoneForwarded: LucideIcon
  export const PhoneIncoming: LucideIcon
  export const PhoneMissed: LucideIcon
  export const PhoneOff: LucideIcon
  export const PhoneOutgoing: LucideIcon
  export const Pi: LucideIcon
  export const Piano: LucideIcon
  export const Pickaxe: LucideIcon
  export const PictureInPicture: LucideIcon
  export const PictureInPicture2: LucideIcon
  export const PiggyBank: LucideIcon
  export const Pill: LucideIcon
  export const PillBottle: LucideIcon
  export const Pin: LucideIcon
  export const PinOff: LucideIcon
  export const Pipette: LucideIcon
  export const Pizza: LucideIcon
  export const Plane: LucideIcon
  export const PlaneLanding: LucideIcon
  export const PlaneTakeoff: LucideIcon
  export const Play: LucideIcon
  export const PlayCircle: LucideIcon
  export const Plug: LucideIcon
  export const Plug2: LucideIcon
  export const Plus: LucideIcon
  export const PlusCircle: LucideIcon
  export const PlusSquare: LucideIcon
  export const Pocket: LucideIcon
  export const PocketKnife: LucideIcon
  export const Popcorn: LucideIcon
  export const Popsicle: LucideIcon
  export const PoundSterling: LucideIcon
  export const Power: LucideIcon
  export const PowerOff: LucideIcon
  export const Presentation: LucideIcon
  export const Printer: LucideIcon
  export const Projector: LucideIcon
  export const Proportions: LucideIcon
  export const Puzzle: LucideIcon
  export const Pyramid: LucideIcon
  export const QrCode: LucideIcon
  export const Quote: LucideIcon
  export const Rabbit: LucideIcon
  export const Radar: LucideIcon
  export const Radio: LucideIcon
  export const RadioReceiver: LucideIcon
  export const RectangleEllipsis: LucideIcon
  export const RectangleHorizontal: LucideIcon
  export const RectangleVertical: LucideIcon
  export const Recycle: LucideIcon
  export const Redo: LucideIcon
  export const Redo2: LucideIcon
  export const RedoDot: LucideIcon
  export const RefreshCcw: LucideIcon
  export const RefreshCw: LucideIcon
  export const Refrigerator: LucideIcon
  export const Regex: LucideIcon
  export const Repeat: LucideIcon
  export const Repeat1: LucideIcon
  export const Repeat2: LucideIcon
  export const Replace: LucideIcon
  export const Resize: LucideIcon
  export const ResizeColumn: LucideIcon
  export const ResizeRow: LucideIcon
  export const Rewind: LucideIcon
  export const Ribbon: LucideIcon
  export const Rocket: LucideIcon
  export const RockingChair: LucideIcon
  export const RollerCoaster: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const RotateCcwSquare: LucideIcon
  export const RoundedRectangle: LucideIcon
  export const Route: LucideIcon
  export const RouteOff: LucideIcon
  export const Router: LucideIcon
  export const Rows: LucideIcon
  export const Rss: LucideIcon
  export const Ruler: LucideIcon
  export const RulerDimensionLine: LucideIcon
  export const Save: LucideIcon
  export const SaveAll: LucideIcon
  export const SaveOff: LucideIcon
  export const Scale: LucideIcon
  export const Scale3D: LucideIcon
  export const Scaling: LucideIcon
  export const Scan: LucideIcon
  export const ScanBarcode: LucideIcon
  export const ScanEye: LucideIcon
  export const ScanFace: LucideIcon
  export const ScanLine: LucideIcon
  export const ScanSearch: LucideIcon
  export const ScanText: LucideIcon
  export const School: LucideIcon
  export const Scissors: LucideIcon
  export const ScreenShare: LucideIcon
  export const ScreenShareOff: LucideIcon
  export const Scroll: LucideIcon
  export const ScrollText: LucideIcon
  export const Search: LucideIcon
  export const SearchCheck: LucideIcon
  export const SearchCode: LucideIcon
  export const SearchSlash: LucideIcon
  export const SearchX: LucideIcon
  export const Send: LucideIcon
  export const SendHorizontal: LucideIcon
  export const SendToBack: LucideIcon
  export const SeparatorHorizontal: LucideIcon
  export const SeparatorVertical: LucideIcon
  export const Server: LucideIcon
  export const ServerCog: LucideIcon
  export const ServerCrash: LucideIcon
  export const ServerOff: LucideIcon
  export const Settings: LucideIcon
  export const Settings2: LucideIcon
  export const Share: LucideIcon
  export const Share2: LucideIcon
  export const Sheet: LucideIcon
  export const Shield: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldCheck: LucideIcon
  export const ShieldMinus: LucideIcon
  export const ShieldOff: LucideIcon
  export const ShieldPlus: LucideIcon
  export const ShieldX: LucideIcon
  export const Ship: LucideIcon
  export const ShipWheel: LucideIcon
  export const Shirt: LucideIcon
  export const ShoppingBag: LucideIcon
  export const ShoppingCart: LucideIcon
  export const Shovel: LucideIcon
  export const ShowerHead: LucideIcon
  export const Shrink: LucideIcon
  export const Shuffle: LucideIcon
  export const Sigma: LucideIcon
  export const Signal: LucideIcon
  export const SignalHigh: LucideIcon
  export const SignalLow: LucideIcon
  export const SignalMedium: LucideIcon
  export const SignalZero: LucideIcon
  export const Signature: LucideIcon
  export const Signpost: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Skull: LucideIcon
  export const Slack: LucideIcon
  export const Slash: LucideIcon
  export const Slice: LucideIcon
  export const SlidersHorizontal: LucideIcon
  export const SlidersVertical: LucideIcon
  export const Smartphone: LucideIcon
  export const SmartphoneCharging: LucideIcon
  export const SmartphoneNfc: LucideIcon
  export const Smile: LucideIcon
  export const SmilePlus: LucideIcon
  export const Snowflake: LucideIcon
  export const Sofa: LucideIcon
  export const SortAsc: LucideIcon
  export const SortDesc: LucideIcon
  export const Speaker: LucideIcon
  export const Sphere: LucideIcon
  export const Spiral: LucideIcon
  export const SplitSquareHorizontal: LucideIcon
  export const SplitSquareVertical: LucideIcon
  export const Square: LucideIcon
  export const SquareArrowDown: LucideIcon
  export const SquareArrowLeft: LucideIcon
  export const SquareArrowRight: LucideIcon
  export const SquareArrowUp: LucideIcon
  export const SquareAsterisk: LucideIcon
  export const SquareCheck: LucideIcon
  export const SquareCheckBig: LucideIcon
  export const SquareDashed: LucideIcon
  export const SquareDot: LucideIcon
  export const SquareEqual: LucideIcon
  export const SquareFunction: LucideIcon
  export const SquareKanban: LucideIcon
  export const SquareMinus: LucideIcon
  export const SquareMousePointer: LucideIcon
  export const SquareParking: LucideIcon
  export const SquarePen: LucideIcon
  export const SquarePi: LucideIcon
  export const SquarePlus: LucideIcon
  export const SquarePower: LucideIcon
  export const SquareRadical: LucideIcon
  export const SquareScissors: LucideIcon
  export const SquareSigma: LucideIcon
  export const SquareSlash: LucideIcon
  export const SquareSplitHorizontal: LucideIcon
  export const SquareSplitVertical: LucideIcon
  export const SquareStack: LucideIcon
  export const SquareTerminal: LucideIcon
  export const SquareUser: LucideIcon
  export const SquareX: LucideIcon
  export const Stack: LucideIcon
  export const Stamp: LucideIcon
  export const Star: LucideIcon
  export const StarHalf: LucideIcon
  export const StarOff: LucideIcon
  export const StepBack: LucideIcon
  export const StepForward: LucideIcon
  export const Stethoscope: LucideIcon
  export const Sticker: LucideIcon
  export const StickyNote: LucideIcon
  export const StopCircle: LucideIcon
  export const Store: LucideIcon
  export const StretchHorizontal: LucideIcon
  export const StretchVertical: LucideIcon
  export const Strikethrough: LucideIcon
  export const Subscript: LucideIcon
  export const Sun: LucideIcon
  export const SunDim: LucideIcon
  export const SunMedium: LucideIcon
  export const SunMoon: LucideIcon
  export const SunSnow: LucideIcon
  export const Superscript: LucideIcon
  export const SwatchBook: LucideIcon
  export const SwissFranc: LucideIcon
  export const SwitchCamera: LucideIcon
  export const Sword: LucideIcon
  export const Swords: LucideIcon
  export const Syringe: LucideIcon
  export const Table: LucideIcon
  export const Table2: LucideIcon
  export const TableCellsMerge: LucideIcon
  export const TableCellsSplit: LucideIcon
  export const TableColumnsSplit: LucideIcon
  export const TableProperties: LucideIcon
  export const TableRowsSplit: LucideIcon
  export const Tablet: LucideIcon
  export const TabletSmartphone: LucideIcon
  export const Tablets: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Tally1: LucideIcon
  export const Tally2: LucideIcon
  export const Tally3: LucideIcon
  export const Tally4: LucideIcon
  export const Tally5: LucideIcon
  export const Terminal: LucideIcon
  export const TerminalSquare: LucideIcon
  export const TestTube: LucideIcon
  export const TestTube2: LucideIcon
  export const TestTubes: LucideIcon
  export const Text: LucideIcon
  export const TextCursor: LucideIcon
  export const TextCursorInput: LucideIcon
  export const TextQuote: LucideIcon
  export const TextSearch: LucideIcon
  export const TextSelect: LucideIcon
  export const Theater: LucideIcon
  export const Thermometer: LucideIcon
  export const ThermometerSun: LucideIcon
  export const ThermometerSnowflake: LucideIcon
  export const ThumbsDown: LucideIcon
  export const ThumbsUp: LucideIcon
  export const Ticket: LucideIcon
  export const TicketPercent: LucideIcon
  export const Timer: LucideIcon
  export const TimerOff: LucideIcon
  export const TimerReset: LucideIcon
  export const ToggleLeft: LucideIcon
  export const ToggleRight: LucideIcon
  export const Tornado: LucideIcon
  export const Torus: LucideIcon
  export const Touchpad: LucideIcon
  export const TouchpadOff: LucideIcon
  export const TowerControl: LucideIcon
  export const ToyBrick: LucideIcon
  export const Tractor: LucideIcon
  export const TrafficCone: LucideIcon
  export const Train: LucideIcon
  export const TrainFront: LucideIcon
  export const TrainFrontTunnel: LucideIcon
  export const TrainTrack: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const TreeDeciduous: LucideIcon
  export const TreePine: LucideIcon
  export const Trees: LucideIcon
  export const Trello: LucideIcon
  export const TrendingDown: LucideIcon
  export const TrendingUp: LucideIcon
  export const Triangle: LucideIcon
  export const TriangleAlert: LucideIcon
  export const TriangleRight: LucideIcon
  export const Trophy: LucideIcon
  export const Truck: LucideIcon
  export const Type: LucideIcon
  export const Umbrella: LucideIcon
  export const UmbrellaOff: LucideIcon
  export const Underline: LucideIcon
  export const Undo: LucideIcon
  export const Undo2: LucideIcon
  export const UndoDot: LucideIcon
  export const UnfoldHorizontal: LucideIcon
  export const UnfoldVertical: LucideIcon
  export const Unlink: LucideIcon
  export const Unlink2: LucideIcon
  export const Unplug: LucideIcon
  export const Upload: LucideIcon
  export const UploadCloud: LucideIcon
  export const Usb: LucideIcon
  export const User: LucideIcon
  export const UserCheck: LucideIcon
  export const UserCog: LucideIcon
  export const UserMinus: LucideIcon
  export const UserPlus: LucideIcon
  export const UserRound: LucideIcon
  export const UserRoundCheck: LucideIcon
  export const UserRoundCog: LucideIcon
  export const UserRoundMinus: LucideIcon
  export const UserRoundPlus: LucideIcon
  export const UserRoundSearch: LucideIcon
  export const UserRoundX: LucideIcon
  export const UserSearch: LucideIcon
  export const UserX: LucideIcon
  export const Users: LucideIcon
  export const UsersRound: LucideIcon
  export const Utensils: LucideIcon
  export const UtensilsCrossed: LucideIcon
  export const Variable: LucideIcon
  export const Vault: LucideIcon
  export const VectorSquare: LucideIcon
  export const Vegan: LucideIcon
  export const VenetianMask: LucideIcon
  export const Vibrate: LucideIcon
  export const VibrateOff: LucideIcon
  export const Video: LucideIcon
  export const VideoOff: LucideIcon
  export const Videotape: LucideIcon
  export const View: LucideIcon
  export const Voicemail: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Vote: LucideIcon
  export const Wallet: LucideIcon
  export const WalletCards: LucideIcon
  export const WalletMinimal: LucideIcon
  export const Wand2: LucideIcon
  export const Warehouse: LucideIcon
  export const Watch: LucideIcon
  export const Waves: LucideIcon
  export const Waypoints: LucideIcon
  export const Webcam: LucideIcon
  export const Webhook: LucideIcon
  export const Weight: LucideIcon
  export const Wheat: LucideIcon
  export const WheatOff: LucideIcon
  export const WholeWord: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const WifiPen: LucideIcon
  export const WifiLow: LucideIcon
  export const WifiHigh: LucideIcon
  export const WifiZero: LucideIcon
  export const Wind: LucideIcon
  export const Window: LucideIcon
  export const WindowMaximize: LucideIcon
  export const WindowMinimize: LucideIcon
  export const Wine: LucideIcon
  export const WineOff: LucideIcon
  export const Workflow: LucideIcon
  export const WrapText: LucideIcon
  export const Wrench: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
  export const XOctagon: LucideIcon
  export const XSquare: LucideIcon
  export const Youtube: LucideIcon
  export const Zap: LucideIcon
  export const ZoomIn: LucideIcon
  export const ZoomOut: LucideIcon
}